### ISSUE TITLE
Enhancement: Add domain-specific keyword dictionaries and skill categorization

### ISSUE THREAD

**Issue by JoshuaOliphant** [JoshuaOliphant/ResumeAIAssistant#136]
## Overview
Implement domain-specific keyword dictionaries and configurable skill categorization to improve the relevance and accuracy of keyword extraction in RelevanceImpactEvaluator.

## Current Limitation
The current implementation uses a hardcoded list of technical keywords that is limited and generic:
```python
tech_keywords = [
    'python', 'javascript', 'java', 'react', 'node.js', 'aws', 'docker', 'kubernetes',
    'sql', 'postgresql', 'mongodb', 'git', 'ci/cd', 'agile', 'scrum', 'api', 'rest',
    'microservices', 'cloud', 'devops', 'machine learning', 'ai', 'data', 'analytics'
]
```

## Problems
- One-size-fits-all approach doesn't work across industries
- Missing industry-specific terminology
- No differentiation between skill categories
- No weighting for skill importance
- Static list requires code changes to update

### 1. Domain-Specific Dictionaries
Create configurable keyword dictionaries for different industries:
- **Technology**: Programming languages, frameworks, tools
- **Healthcare**: Medical terminology, certifications, systems
- **Finance**: Financial instruments, regulations, software
- **Marketing**: Platforms, strategies, analytics tools
- **Engineering**: CAD software, methodologies, standards

### 2. Skill Categorization
Implement weighted categories:
```python
skill_categories = {
    "core_technical": {"weight": 1.0, "keywords": [...]},
    "tools_platforms": {"weight": 0.8, "keywords": [...]},
    "methodologies": {"weight": 0.6, "keywords": [...]},
    "soft_skills": {"weight": 0.4, "keywords": [...]}
}
```

### 3. Dynamic Configuration
- Load dictionaries from JSON/YAML files
- Support custom dictionaries per evaluation
- Allow runtime updates without code changes
- Industry detection from job description

### 4. Hierarchical Keywords
Support related term grouping:
```json
{
  "cloud_platforms": {
    "aws": ["ec2", "s3", "lambda", "rds"],
    "azure": ["blob", "functions", "cosmos"],
    "gcp": ["compute engine", "cloud storage", "bigquery"]
  }
}
```

## Implementation Design
```python
class DomainKeywordManager:
    def __init__(self, domain: str = "technology"):
        self.domain = domain
        self.keywords = self._load_domain_keywords()
    
    def _load_domain_keywords(self) -> Dict[str, List[str]]:
        # Load from configuration files
        pass
    
    def get_weighted_keywords(self, job_description: str) -> Dict[str, float]:
        # Return keywords with importance weights
        pass
    
    def detect_domain(self, text: str) -> str:
        # Auto-detect industry from job description
        pass
```

## Configuration Example
```yaml
# keywords/technology.yaml
domain: technology
categories:
  programming_languages:
    weight: 1.0
    keywords:
      - python
      - java
      - javascript
      - typescript
      - go
      - rust
  
  frameworks:
    weight: 0.9
    keywords:
      frontend:
        - react
        - angular
        - vue
      backend:
        - django
        - spring
        - express
  
  databases:
    weight: 0.8
    keywords:
      relational:
        - postgresql
        - mysql
        - oracle
      nosql:
        - mongodb
        - cassandra
        - redis
```

## Benefits
- Industry-specific accuracy
- Easily maintainable keyword lists
- Weighted importance for better scoring
- Hierarchical relationships captured
- No code changes for keyword updates

## Integration Points
- `_extract_keywords()` method enhancement
- Configuration loading at evaluator initialization
- Domain detection from job descriptions
- Weighted scoring in keyword coverage calculation

## Related Files
- `evaluation/evaluators/quality.py`
- New directory: `evaluation/keywords/` for domain files

**Priority**: Medium
**Estimated Effort**: 2-3 days
**Related to**: #114, #128
